CREATE schema COMMANDSERVER;

CREATE TABLE COMMANDSERVER.USERNAME_EMAIL (
    USER_NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(320) NOT NULL,
    PRIMARY KEY (USER_NAME, EMAIL),
    CONSTRAINT UNIQUE_USER_NAME UNIQUE (USER_NAME),
    CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL)
);

CREATE SEQUENCE COMMANDSERVER.CATEGORY_ID AS BIGINT START WITH 1;

CREATE TABLE COMMANDSERVER.CATEGORY_NAMES (
    NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (NAME)
);
